name: Year Tracker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup node v21
      uses: actions/setup-node@v1
      with:
        node-version: '*'
    - name: Run README.md update script
      run: node scripts/yearTracker.js > README.md
    - name: Commit change & Push
      run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am "bot: Update year tracker in README.md (auto)"
          git push